version: '3'
services:
  odoo:
    build:
        args:
            host_uid: 1000
            host_gid: 1000
        target: local
    volumes:
        - .:/workspace:cached
        - ./odoo/parse_db_url.sh:/usr/local/lib/parse_db_url.sh
        - ./odoo/entrypoint.sh/:/entrypoint.sh
        - ./odoo/odoo_cmds:/usr/local/bin/odoo_cmds
        - projectname-bashhistory:/commandhistory
        - vs-code-extensions:/odoo/.vscode-server/extensions
        - odoo-lib:/var/lib/odoo
    command: sleep infinity

volumes:
    projectname-bashhistory:
    vs-code-extensions:
    odoo-lib: