# fly.toml file generated for dizzyhub-pg on 2021-07-10T18:44:30-07:00

# app = "dizzyhub-pg"

kill_signal = "SIGINT"
kill_timeout = 5


[env]
POSTGRES_PASSWORD = ""
POSTGRES_USER = "lizzie"
POSTGRES_DB = "lizzie"
PGDATA  = "/var/lib/postgresql/data/pgdata"

[mounts]
source = "pg_data"
destination = "/var/lib/postgresql/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 5432
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 20
    soft_limit = 5
    type = "connections"

  [[services.ports]]
    port = 5000


  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
