default_context:
  project_name: 'datahub'
  project_slug: 'datahub'
  domain_main: 'datahub.com'
  domain_staging: 'stag.datahub.com'
  docker_swarm_stack_name_main: 'datahub-com'
  docker_swarm_stack_name_staging: 'stag-datahub-com'
  secret_key: 'password'
  first_superuser: 'admin@local'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.datahub.com", "https://stag.datahub.com", "https://datahub.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@datahub.com'
  postgres_password: 'password'
  pgadmin_default_user: 'password'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'datahub.com'
  traefik_constraint_tag_staging: 'stag.datahub.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: 'https://de3a66b5710e434bbfb4d77151f7fef7@o944926.ingest.sentry.io/5893436'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
